version: "3.8"

services:
  php8.0:
    image: php8.0:latest
    container_name: php8.0
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: php8.0
    restart: always
    volumes:
      - /www:/var/www/html

networks:
  default:
    external:
      name: php_network