version: "3.8"

services:
  php8.2.5:
    image: php8.2.5:latest
    container_name: php8.2.5
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: php8.2.5
    restart: always
    volumes:
      - /www:/var/www/html

networks:
  default:
    external:
      name: php_network