version: "3.8"

services:
  elasticsearch8.8.1:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.1
    container_name: es
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: elasticsearch8.8.1
    restart: always
    volumes:
      - ./volume/config:/usr/share/elasticsearch/config
      - /home/es/logs:/usr/share/elasticsearch/logs
      - /home/es/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      discovery.type: single-node

networks:
  default:
    external:
      name: elasticsearch_network