version: "3.8"

services:
  nginx1.18.0:
    image: nginx1.18.0:latest
    container_name: nginx1.18.0
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: nginx1.18.0
    restart: always
    volumes:
      - ./volume/log:/var/log/nginx
      - ./volume/conf.d:/etc/nginx/conf.d
      - ./volume/conf/nginx.conf:/etc/nginx/nginx.conf
      - /www:/usr/share/nginx/html
    ports:
      - "80:80"

networks:
  default:
    external:
      name: nginx_network